services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:9
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@epsandes.com
      - PGADMIN_DEFAULT_PASSWORD=passwd
    ports:
      - 80:80
    depends_on:
      - postgres
  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - 3000:3000
    depends_on:
      - prometheus
